//! Contract operations: export rules and check code invariants with ast-grep.

use std::path::Path;
use std::process::Command;

use anyhow::{Context, Result};
use serde::Deserialize;

use crate::domain::{Contract, ContractSeverity, Fact, FactId};
use crate::store::Store;

use super::{find_ast_grep, infer_language, CheckOptions, ContractCheckReport, ContractViolation, ExportReport};

/// Generates the YAML representation of a single ast-grep rule.
pub fn rule_to_yaml(fact_id: &FactId, title: &str, contract: &Contract) -> String {
    let rule_id = format!("uma-{}", fact_id.to_string().to_lowercase());
    let severity = match contract.severity {
        ContractSeverity::Deny => "error",
        ContractSeverity::Warn => "warning",
    };
    let language = infer_language(contract, None);

    let mut out = String::new();
    out.push_str(&format!("id: {rule_id}\n"));
    out.push_str(&format!("message: \"{}\"\n", contract.rule.message.replace('"', "\\\"")));
    out.push_str(&format!("severity: {severity}\n"));
    out.push_str(&format!("language: {language}\n"));
    out.push_str("metadata:\n");
    out.push_str(&format!("  fact_id: \"{}\"\n", fact_id));
    out.push_str(&format!("  title: \"{}\"\n", title.replace('"', "\\\"")));
    out.push_str("rule:\n");
    out.push_str(&format!("  pattern: \"{}\"\n", contract.rule.pattern.replace('"', "\\\"")));
    if let Some(ref inside) = contract.rule.inside {
        out.push_str(&format!("  inside:\n    stopBy: end\n    pattern: \"$$$\"\n"));
        out.push_str(&format!("files:\n  - \"{}\"\n", inside));
    }
    out
}

/// Compiles and exports all active contracts from `store` into `target_dir`.
pub fn export_contracts(store: &Store, target_dir: &Path) -> Result<ExportReport> {
    std::fs::create_dir_all(target_dir)
        .with_context(|| format!("Failed to create contract directory {:?}", target_dir))?;

    let sgconfig_path = target_dir.join("sgconfig.yml");
    let sgconfig_content = "ruleDirs:\n  - .\n";
    std::fs::write(&sgconfig_path, sgconfig_content)
        .with_context(|| format!("Failed to write {:?}", sgconfig_path))?;

    let now = chrono::Utc::now();
    let facts = store.list_all()?;
    let mut count = 0usize;
    let mut test_cases = Vec::new();

    for fact in &facts {
        if !fact.is_active_at(now) {
            continue;
        }
        let Some(ref contract) = fact.contract else {
            continue;
        };

        let file_name = format!("{}.yml", fact.id.to_string().to_lowercase());
        let rule_path = target_dir.join(&file_name);
        let yaml = rule_to_yaml(&fact.id, &fact.title, contract);

        std::fs::write(&rule_path, yaml)
            .with_context(|| format!("Failed to write rule to {:?}", rule_path))?;
        count += 1;

        let safe_title = fact
            .title
            .chars()
            .map(|c| if c.is_alphanumeric() { c.to_ascii_lowercase() } else { '_' })
            .collect::<String>();
        test_cases.push((fact.id.to_string(), safe_title, file_name, fact.title.clone()));
    }

    let mut test_harness = None;
    if let Ok(git_root) = Store::find_git_root() {
        let tests_dir = git_root.join("tests");
        if tests_dir.exists() || git_root.join("Cargo.toml").exists() {
            let _ = std::fs::create_dir_all(&tests_dir);
            let harness_path = tests_dir.join("architecture_invariants.rs");

            let mut code = String::new();
            code.push_str("//! Generated by UMA (Universal Memory Architecture).\n");
            code.push_str("//! Invariants compiled directly from active memory decisions.\n\n");

            for (id, safe_title, rule_file, title) in &test_cases {
                code.push_str(&format!(
                    "#[test]\nfn invariant_{}_{}() {{\n",
                    &id[..8].to_lowercase(),
                    safe_title
                ));
                code.push_str(&format!("    // Memory Decision: {}\n", title));
                code.push_str("    let ast_grep = if cfg!(windows) { \"ast-grep.exe\" } else { \"ast-grep\" };\n");
                code.push_str(&format!(
                    "    let output = match std::process::Command::new(ast_grep)\n        .args([\"scan\", \"--rule\", \".uma/contracts/{}\"])\n        .output() {{\n            Ok(o) => o,\n            Err(_) => match std::process::Command::new(\"sg\")\n                .args([\"scan\", \"--rule\", \".uma/contracts/{}\"])\n                .output() {{\n                Ok(o) => o,\n                Err(_) => {{\n                    eprintln!(\"ast-grep not found — skipping architecture invariant test\");\n                    return;\n                }}\n            }},\n        }};\n\n",
                    rule_file, rule_file
                ));
                code.push_str(&format!(
                    "    assert!(output.status.success(), \"Architecture invariant [{}] violated!\\n{{}}\", String::from_utf8_lossy(&output.stdout));\n",
                    id
                ));
                code.push_str("}\n\n");
            }

            if std::fs::write(&harness_path, code).is_ok() {
                test_harness = Some(harness_path);
            }
        }
    }

    Ok(ExportReport {
        contracts_exported: count,
        target_dir: target_dir.to_path_buf(),
        test_harness,
    })
}

/// Runs a deterministic contract check against the codebase or a specific path.
pub fn check_contracts(store: &Store, options: &CheckOptions) -> Result<ContractCheckReport> {
    let now = chrono::Utc::now();
    let facts = store.list_all()?;
    let contract_facts: Vec<&Fact> = facts
        .iter()
        .filter(|f| f.is_active_at(now) && f.contract.is_some())
        .collect();

    if contract_facts.is_empty() {
        return Ok(ContractCheckReport {
            engine: "none".to_string(),
            rules_checked: 0,
            violations: Vec::new(),
            clean: true,
            notes: Some("No active memory facts with contracts found.".to_string()),
        });
    }

    let Some(ast_grep_bin) = find_ast_grep() else {
        return Ok(ContractCheckReport {
            engine: "ast-grep (unavailable)".to_string(),
            rules_checked: contract_facts.len(),
            violations: Vec::new(),
            clean: true,
            notes: Some(
                "ast-grep executable not found. Install via 'npm install -g @ast-grep/cli' or cargo."
                    .to_string(),
            ),
        });
    };

    let git_root = Store::find_git_root().unwrap_or_else(|_| std::env::current_dir().unwrap_or_default());
    let contracts_dir = git_root.join(".uma").join("contracts");

    if !contracts_dir.join("sgconfig.yml").exists() {
        let _ = export_contracts(store, &contracts_dir);
    }

    let sgconfig_path = contracts_dir.join("sgconfig.yml");
    let mut cmd = Command::new(&ast_grep_bin);
    cmd.current_dir(&git_root);
    cmd.args(["scan", "--json=compact", "--config"]);
    cmd.arg(&sgconfig_path);

    if let Some(ref path) = options.path_filter {
        cmd.arg(path);
    }

    if let Some(ref filter) = options.rule_filter {
        cmd.args(["--filter", filter]);
    }

    let output = cmd.output().context("Failed to execute ast-grep scan")?;
    let stdout = String::from_utf8_lossy(&output.stdout);

    #[derive(Deserialize)]
    struct AstGrepMatch {
        file: String,
        lines: String,
        #[serde(rename = "ruleId")]
        rule_id: String,
        severity: String,
        message: Option<String>,
        range: AstGrepRange,
    }

    #[derive(Deserialize)]
    struct AstGrepRange {
        start: AstGrepPos,
    }

    #[derive(Deserialize)]
    struct AstGrepPos {
        line: usize,
    }

    let matches: Vec<AstGrepMatch> = serde_json::from_str(stdout.trim()).unwrap_or_default();
    let mut violations = Vec::new();

    for m in matches {
        let fact_id = m
            .rule_id
            .strip_prefix("uma-")
            .unwrap_or(&m.rule_id)
            .to_uppercase();

        let matching_fact = contract_facts.iter().find(|f| {
            f.id.to_string().to_uppercase() == fact_id
                || f.id.to_string().to_lowercase() == fact_id.to_lowercase()
        });

        let severity = matching_fact
            .and_then(|f| f.contract.as_ref().map(|c| c.severity))
            .unwrap_or(if m.severity == "error" {
                ContractSeverity::Deny
            } else {
                ContractSeverity::Warn
            });

        let message = m.message.unwrap_or_else(|| {
            matching_fact
                .and_then(|f| f.contract.as_ref().map(|c| c.rule.message.clone()))
                .unwrap_or_else(|| "Architecture invariant violation".to_string())
        });

        violations.push(ContractViolation {
            fact_id,
            rule_id: m.rule_id,
            file: m.file,
            line: m.range.start.line + 1,
            message,
            severity,
            snippet: m.lines.trim().to_string(),
        });
    }

    let clean = violations.is_empty();
    Ok(ContractCheckReport {
        engine: "ast-grep".to_string(),
        rules_checked: contract_facts.len(),
        violations,
        clean,
        notes: None,
    })
}
